import { Project, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'CORE', label: 'Platforms & Systems', backgroundLabel: 'SYSTEMS' },
  { id: 'AI', label: 'AI & Automation', backgroundLabel: 'AGENTS' },
  { id: 'SaaS', label: 'Product Apps', backgroundLabel: 'PRODUCT' },
  { id: 'OPEN', label: 'Open Source', backgroundLabel: 'OSS' },
  { id: 'LABS', label: 'Research & Experiments', backgroundLabel: 'LABS' },
];

export const PROJECTS: Project[] = [
  {
    id: 'zawgyi-conv',
    title: 'Unicode ↔ Zawgyi Converter',
    category: 'OPEN',
    description: 'Java implementation of Unicode <-> Zawgyi conversion. A critical interoperability tool for Burmese text processing, handling complex encoding transformations.',
    images: ['https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&q=80&w=1600'],
    year: '2015',
    month: 9,
    tagline: 'Myanmar text interoperability.',
    stack: ['Java', 'Unicode', 'Regex'],
    status: 'V1.0',
    origin: 'Hand-Coded',
    platform: 'System',
    role: 'Backend',
    iconColor: '#34D399',
    tier: 'secondary',
    deployTarget: 'Library/CLI',
    securityProfile: 'N/A',
    githubLink: 'https://github.com/minthanthtoo/UnicodeZawgyiConverter'
  },
  {
    id: 'my-collation',
    title: 'Myanmar Collation Stats',
    category: 'OPEN',
    description: 'Lexicon analyzer focused on sorting/collation and segmentation rules for the Myanmar language. Built for NLP and search indexing efficiency.',
    images: ['https://images.unsplash.com/photo-1508163223045-1880bc36e222?auto=format&fit=crop&q=80&w=1600'],
    year: '2021',
    month: 8,
    tagline: 'Language collation + segmentation.',
    stack: ['Java', 'NLP', 'Unicode'],
    status: 'V1.0',
    origin: 'Hand-Coded',
    platform: 'System',
    role: 'Backend',
    iconColor: '#60A5FA',
    tier: 'secondary',
    deployTarget: 'Library/CLI',
    securityProfile: 'N/A',
    githubLink: 'https://github.com/minthanthtoo/myanmar-collation-stats'
  },
  {
    id: 'myangrow',
    title: 'myangrow (AI Scaffold)',
    category: 'SaaS',
    description: 'A rapid deployment scaffold built for AI Studio workflows. Demonstrates prompt-to-deployment velocity and modern front-end scaffolding.',
    images: ['https://images.unsplash.com/photo-1557825835-70d97c4aa567?auto=format&fit=crop&q=80&w=1600'],
    year: '2025',
    month: 2,
    tagline: 'Vibe-coded deployment scaffold.',
    stack: ['TypeScript', 'React', 'AI Studio'],
    status: 'Beta',
    origin: 'Vibe-Coded',
    platform: 'Web',
    role: 'Frontend',
    iconColor: '#F472B6',
    tier: 'secondary',
    deployTarget: 'Static Site',
    securityProfile: 'Public-only',
    githubLink: 'https://github.com/minthanthtoo/myangrow'
  },
  {
    id: 'myango',
    title: 'myango',
    category: 'SaaS',
    description: 'Showcase entry for the myango product app. Recommended architecture is frontend static hosting with a backend/API layer for protected operations.',
    images: ['https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&q=80&w=1600'],
    year: '2025',
    month: 3,
    tagline: 'Product app architecture showcase.',
    stack: ['JavaScript', 'React', 'Supabase'],
    status: 'Beta',
    origin: 'Hand-Coded',
    platform: 'Web',
    role: 'Fullstack',
    iconColor: '#38BDF8',
    tier: 'flagship',
    deployTarget: 'Static + API',
    securityProfile: 'Public + RLS',
    githubLink: 'https://github.com/minthanthtoo/myango'
  },
  {
    id: 'dsp-roadmap',
    title: 'DSP Roadmap',
    category: 'OPEN',
    description: 'A 16-week Digital Signal Processing curriculum. Includes Jupyter notebooks, applied projects, and mathematical foundations for mastering signals.',
    images: ['https://images.unsplash.com/photo-1518779578993-ec3579fee39f?auto=format&fit=crop&q=80&w=1600'],
    year: '2025',
    month: 4,
    tagline: 'Mastering signal processing.',
    stack: ['Python', 'Jupyter', 'DSP', 'Mathematics'],
    status: 'V1.0',
    origin: 'Hand-Coded',
    platform: 'System',
    role: 'Backend',
    iconColor: '#F59E0B',
    tier: 'flagship',
    deployTarget: 'Static Site',
    securityProfile: 'Public-only',
    githubLink: 'https://github.com/minthanthtoo/signal-processing-roadmap'
  },
  {
    id: 'audio-dsp',
    title: 'Audio Signal Processing',
    category: 'OPEN',
    description: 'Practical DSP mini-projects including FFT analysis, noise cancellation, and pitch shifting. A lab-style repository for applied signal engineering.',
    images: ['https://images.unsplash.com/photo-1516280030429-27679b3dc9cf?auto=format&fit=crop&q=80&w=1600'],
    year: '2025',
    month: 4,
    tagline: 'Applied audio engineering.',
    stack: ['Python', 'DSP', 'STFT', 'NumPy'],
    status: 'Beta',
    origin: 'Hand-Coded',
    platform: 'System',
    role: 'Backend',
    iconColor: '#FB7185',
    tier: 'secondary',
    deployTarget: 'Research Artifact',
    securityProfile: 'N/A',
    githubLink: 'https://github.com/minthanthtoo/audio-signal-processing'
  },
  {
    id: 'gemini-router',
    title: 'Gemini Router',
    category: 'CORE',
    description: 'Advanced LLM infrastructure layer with tiering, key rotation, and health probing. Persists usage stats and optimizes request routing across multiple providers.',
    images: ['https://images.unsplash.com/photo-1558494949-ef010cbdcc51?auto=format&fit=crop&q=80&w=1600'],
    year: '2025',
    month: 6,
    tagline: 'High-availability LLM infra.',
    stack: ['Python', 'Asyncio', 'Redis', 'LLM Infra'],
    status: 'Production',
    origin: 'Hand-Coded',
    platform: 'System',
    role: 'Backend',
    iconColor: '#10B981',
    tier: 'flagship',
    deployTarget: 'Web Service',
    securityProfile: 'Server secrets',
    githubLink: 'https://github.com/minthanthtoo/gemini-router'
  },
  {
    id: 'smartdoc',
    title: 'SmartDoc Engine',
    category: 'CORE',
    description: 'Modular document intelligence platform for OCR, automated redaction, and table extraction. Ships as a robust REST API with a multi-module endpoint layout.',
    images: ['https://images.unsplash.com/photo-1558494949-ef010cbdcc51?auto=format&fit=crop&q=80&w=1600'],
    year: '2025',
    month: 7,
    tagline: 'Modular document intelligence.',
    stack: ['Python', 'Docker', 'REST API', 'OCR'],
    status: 'V1.0',
    origin: 'Hand-Coded',
    platform: 'System',
    role: 'Fullstack',
    iconColor: '#22C55E',
    tier: 'flagship',
    deployTarget: 'Web Service',
    securityProfile: 'Server secrets',
    githubLink: 'https://github.com/minthanthtoo/smartdoc-engine-public'
  },
  {
    id: 'jepa-agi',
    title: 'JEPA AGI Prototype',
    category: 'LABS',
    description: 'Experimental latent learning pipeline based on the JEPA architecture. Explores self-supervised training loops, world-models, and vector memory systems.',
    images: ['https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=1600'],
    year: '2025',
    month: 11,
    tagline: 'Latent learning experiments.',
    stack: ['Python', 'PyTorch', 'RL', 'Agents'],
    status: 'Lab',
    origin: 'Hand-Coded',
    platform: 'System',
    role: 'Backend',
    iconColor: '#F97316',
    tier: 'flagship',
    deployTarget: 'Web Service',
    securityProfile: 'Server secrets',
    githubLink: 'https://github.com/minthanthtoo/jepa_agi'
  },
  {
    id: 'tb-calendar',
    title: 'TB Team Calendar',
    category: 'SaaS',
    description: 'Healthcare treatment tracker for patient cycles. Built with Flask and FullCalendar to provide visual clarity for clinical teams managing milestones.',
    images: ['https://images.unsplash.com/photo-1586769852836-bc069f19e1b6?auto=format&fit=crop&q=80&w=1600'],
    year: '2025',
    month: 12,
    tagline: 'Visualizing treatment cycles.',
    stack: ['Python', 'Flask', 'Postgres', 'Healthcare Ops'],
    status: 'V1.0',
    origin: 'Hand-Coded',
    platform: 'Web',
    role: 'Fullstack',
    iconColor: '#06B6D4',
    tier: 'flagship',
    deployTarget: 'Web Service + DB',
    securityProfile: 'Server secrets',
    githubLink: 'https://github.com/minthanthtoo/TB-team-calendar'
  },
  {
    id: 'antigravity',
    title: 'Antigravity Factory',
    category: 'AI',
    description: 'Multi-agent orchestration system that synthesizes research papers into structured LaTeX textbooks. Automates collection, curation, and generation protocol.',
    images: ['https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&q=80&w=1600'],
    year: '2025',
    month: 12,
    tagline: 'Autonomous research synthesis.',
    stack: ['Python', 'Agents', 'LaTeX', 'Automation'],
    status: 'Beta',
    origin: 'Hand-Coded',
    platform: 'System',
    role: 'Backend',
    iconColor: '#A855F7',
    tier: 'flagship',
    deployTarget: 'Web Service',
    securityProfile: 'Server secrets',
    githubLink: 'https://github.com/minthanthtoo/antigravity-factory'
  }
];
