import { Project, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'CORE', label: 'Platforms & Systems', backgroundLabel: 'SYSTEMS' },
  { id: 'AI', label: 'AI & Automation', backgroundLabel: 'AGENTS' },
  { id: 'SaaS', label: 'Product Apps', backgroundLabel: 'PRODUCT' },
  { id: 'OPEN', label: 'Open Source', backgroundLabel: 'OSS' },
  { id: 'LABS', label: 'Research & Experiments', backgroundLabel: 'LABS' },
];

export const PROJECTS: Project[] = [
  {
    id: 'zawgyi-conv',
    title: 'Unicode ↔ Zawgyi Converter',
    category: 'OPEN',
    description: 'Java implementation of Unicode <-> Zawgyi conversion. A critical interoperability tool for Burmese text processing, handling complex encoding transformations.',
    images: ['/project-media/zawgyi-conv/highlight.png', '/project-media/zawgyi-conv/live-01.png', '/project-media/zawgyi-conv/live-02.png', '/project-media/zawgyi-conv/live-03.png'],
    year: '2015',
    month: 9,
    tagline: 'Myanmar text interoperability.',
    stack: ['Java', 'Unicode', 'Regex'],
    status: 'V1.0',
    origin: 'Hand-Coded',
    platform: 'System',
    role: 'Backend',
    iconColor: '#34D399',
    tier: 'secondary',
    deployTarget: 'Library/CLI',
    securityProfile: 'N/A',
    githubLink: 'https://github.com/minthanthtoo/UnicodeZawgyiConverter'
  },
  {
    id: 'my-collation',
    title: 'Myanmar Collation Stats',
    category: 'OPEN',
    description: 'Lexicon analyzer focused on sorting/collation and segmentation rules for the Myanmar language. Built for NLP and search indexing efficiency.',
    images: ['/project-media/my-collation/highlight.png', '/project-media/my-collation/live-01.png', '/project-media/my-collation/live-02.png', '/project-media/my-collation/live-03.png'],
    year: '2021',
    month: 8,
    tagline: 'Language collation + segmentation.',
    stack: ['Java', 'NLP', 'Unicode'],
    status: 'V1.0',
    origin: 'Hand-Coded',
    platform: 'System',
    role: 'Backend',
    iconColor: '#60A5FA',
    tier: 'secondary',
    deployTarget: 'Library/CLI',
    securityProfile: 'N/A',
    githubLink: 'https://github.com/minthanthtoo/myanmar-collation-stats'
  },
  {
    id: 'myangrow',
    title: 'myangrow (AI Scaffold)',
    category: 'SaaS',
    description: 'Burmese-first agri intelligence app with dashboard, map, weather, crop planning, pest diagnostics, and market/community modules. Combines geospatial soil layering, zone drawing, and Gemini-assisted recommendations with offline cache fallback.',
    images: ['/project-media/myangrow/highlight.png', '/project-media/myangrow/live-01.png', '/project-media/myangrow/live-02.png', '/project-media/myangrow/live-03.png'],
    year: '2025',
    month: 2,
    tagline: 'Burmese agri intelligence + geospatial AI.',
    stack: ['TypeScript', 'React', 'Leaflet', 'Gemini API', 'Myanmar Language'],
    status: 'Beta',
    origin: 'Vibe-Coded',
    platform: 'Web',
    role: 'Frontend',
    iconColor: '#F472B6',
    tier: 'secondary',
    deployTarget: 'Static Site',
    securityProfile: 'Public-only',
    liveDemoUrl: 'https://myangrow.onrender.com',
    githubLink: 'https://github.com/minthanthtoo/myangrow'
  },
  {
    id: 'myango',
    title: 'myango',
    category: 'SaaS',
    description: 'Flutter Web deployment published as a static PWA shell (CanvasKit renderer). Current repository ships prebuilt artifacts only, so implementation details and backend integration boundaries are not yet transparent in source.',
    images: ['/project-media/myango/highlight.png', '/project-media/myango/live-01.png', '/project-media/myango/live-02.png', '/project-media/myango/live-03.png'],
    year: '2025',
    month: 3,
    tagline: 'Flutter web deployment baseline.',
    stack: ['Flutter', 'Web', 'Static Hosting', 'PWA'],
    status: 'Beta',
    origin: 'Hand-Coded',
    platform: 'Web',
    role: 'Frontend',
    iconColor: '#38BDF8',
    tier: 'flagship',
    deployTarget: 'Static Site',
    securityProfile: 'Public-only',
    liveDemoUrl: 'https://myango.onrender.com',
    githubLink: 'https://github.com/minthanthtoo/myango'
  },
  {
    id: 'dsp-roadmap',
    title: 'DSP Roadmap',
    category: 'OPEN',
    description: 'A 16-week Digital Signal Processing curriculum. Includes Jupyter notebooks, applied projects, and mathematical foundations for mastering signals.',
    images: ['/project-media/dsp-roadmap/highlight.png', '/project-media/dsp-roadmap/live-01.png', '/project-media/dsp-roadmap/live-02.png', '/project-media/dsp-roadmap/live-03.png'],
    year: '2025',
    month: 4,
    tagline: 'Mastering signal processing.',
    stack: ['Python', 'Jupyter', 'DSP', 'Mathematics'],
    status: 'V1.0',
    origin: 'Hand-Coded',
    platform: 'System',
    role: 'Backend',
    iconColor: '#F59E0B',
    tier: 'flagship',
    deployTarget: 'Static Site',
    securityProfile: 'Public-only',
    githubLink: 'https://github.com/minthanthtoo/signal-processing-roadmap'
  },
  {
    id: 'audio-dsp',
    title: 'Audio Signal Processing',
    category: 'OPEN',
    description: 'Practical DSP mini-projects including FFT analysis, noise cancellation, and pitch shifting. A lab-style repository for applied signal engineering.',
    images: ['/project-media/audio-dsp/highlight.png', '/project-media/audio-dsp/live-01.png', '/project-media/audio-dsp/live-02.png', '/project-media/audio-dsp/live-03.png'],
    year: '2025',
    month: 4,
    tagline: 'Applied audio engineering.',
    stack: ['Python', 'DSP', 'STFT', 'NumPy'],
    status: 'Beta',
    origin: 'Hand-Coded',
    platform: 'System',
    role: 'Backend',
    iconColor: '#FB7185',
    tier: 'secondary',
    deployTarget: 'Research Artifact',
    securityProfile: 'N/A',
    githubLink: 'https://github.com/minthanthtoo/audio-signal-processing'
  },
  {
    id: 'gemini-router',
    title: 'Gemini Router',
    category: 'CORE',
    description: 'Advanced LLM infrastructure layer with tiering, key rotation, and health probing. Persists usage stats and optimizes request routing across multiple providers.',
    images: ['/project-media/gemini-router/highlight.png', '/project-media/gemini-router/live-01.png', '/project-media/gemini-router/live-02.png', '/project-media/gemini-router/live-03.png'],
    year: '2025',
    month: 6,
    tagline: 'High-availability LLM infra.',
    stack: ['Python', 'Asyncio', 'Redis', 'LLM Infra'],
    status: 'Production',
    origin: 'Hand-Coded',
    platform: 'System',
    role: 'Backend',
    iconColor: '#10B981',
    tier: 'flagship',
    deployTarget: 'Web Service',
    securityProfile: 'Server secrets',
    githubLink: 'https://github.com/minthanthtoo/gemini-router'
  },
  {
    id: 'smartdoc',
    title: 'SmartDoc Engine',
    category: 'CORE',
    description: 'Modular document intelligence platform for OCR, automated redaction, and table extraction. Ships as a robust REST API with a multi-module endpoint layout.',
    images: ['/project-media/smartdoc/highlight.png', '/project-media/smartdoc/live-01.png', '/project-media/smartdoc/live-02.png', '/project-media/smartdoc/live-03.png'],
    year: '2025',
    month: 7,
    tagline: 'Modular document intelligence.',
    stack: ['Python', 'Docker', 'REST API', 'OCR'],
    status: 'V1.0',
    origin: 'Hand-Coded',
    platform: 'System',
    role: 'Fullstack',
    iconColor: '#22C55E',
    tier: 'flagship',
    deployTarget: 'Web Service',
    securityProfile: 'Server secrets',
    githubLink: 'https://github.com/minthanthtoo/smartdoc-engine-public'
  },
  {
    id: 'jepa-agi',
    title: 'JEPA AGI Prototype',
    category: 'LABS',
    description: 'Experimental latent learning pipeline based on the JEPA architecture. Explores self-supervised training loops, world-models, and vector memory systems.',
    images: ['/project-media/jepa-agi/highlight.png', '/project-media/jepa-agi/live-01.png', '/project-media/jepa-agi/live-02.png', '/project-media/jepa-agi/live-03.png'],
    year: '2025',
    month: 11,
    tagline: 'Latent learning experiments.',
    stack: ['Python', 'PyTorch', 'RL', 'Agents'],
    status: 'Lab',
    origin: 'Hand-Coded',
    platform: 'System',
    role: 'Backend',
    iconColor: '#F97316',
    tier: 'flagship',
    deployTarget: 'Web Service',
    securityProfile: 'Server secrets',
    githubLink: 'https://github.com/minthanthtoo/jepa_agi'
  },
  {
    id: 'tb-calendar',
    title: 'TB Team Calendar',
    category: 'SaaS',
    description: 'TB treatment operations tracker built with Flask + FullCalendar for milestone timelines, patient outcomes, and team-scoped access. Includes offline cache, delta sync, WiFi peer merge workflows, and invite/approval based multi-team collaboration.',
    images: ['/project-media/tb-calendar/highlight.png', '/project-media/tb-calendar/live-01.png', '/project-media/tb-calendar/live-02.png', '/project-media/tb-calendar/live-03.png'],
    year: '2025',
    month: 12,
    tagline: 'Clinical cycle tracking with team sync.',
    stack: ['Python', 'Flask', 'FullCalendar', 'Postgres/SQLite', 'Healthcare Ops'],
    status: 'V1.0',
    origin: 'Hand-Coded',
    platform: 'Web',
    role: 'Fullstack',
    iconColor: '#06B6D4',
    tier: 'flagship',
    deployTarget: 'Web Service + DB',
    securityProfile: 'Server secrets',
    liveDemoUrl: 'https://tb-team-calendar.onrender.com',
    githubLink: 'https://github.com/minthanthtoo/TB-team-calendar'
  },
  {
    id: 'antigravity',
    title: 'Antigravity Factory',
    category: 'AI',
    description: 'Multi-agent orchestration system that synthesizes research papers into structured LaTeX textbooks. Automates collection, curation, and generation protocol.',
    images: ['/project-media/antigravity/highlight.png', '/project-media/antigravity/live-01.png', '/project-media/antigravity/live-02.png', '/project-media/antigravity/live-03.png'],
    year: '2025',
    month: 12,
    tagline: 'Autonomous research synthesis.',
    stack: ['Python', 'Agents', 'LaTeX', 'Automation'],
    status: 'Beta',
    origin: 'Hand-Coded',
    platform: 'System',
    role: 'Backend',
    iconColor: '#A855F7',
    tier: 'flagship',
    deployTarget: 'Web Service',
    securityProfile: 'Server secrets',
    githubLink: 'https://github.com/minthanthtoo/antigravity-factory'
  }
];
